### ISSUE TITLE
Add to addons.mozilla.org

### ISSUE THREAD

**Issue by ShadowPhantom** [The-breakbar/TISS-Lightning-Registrator#3]
I just tried it. It works perfectly! Thank you so much!!

Why don't you add the Extension to the Firefox store (for automatic updates, etc.)?

I have an extension there as well, it is super easy and does not require any verification like the chrome store does.
They just require email, age and password, if I remember correctly.

If you should need help (which I highly doubt, considering your skills in creating this extension), let me know!

**Comment by The-breakbar** [comment]
Thank you! I am glad it could help you.

I actually did submit it to the Firefox extension store, but unfortunately it got rejected. Their reason was that it was an extension for a "limited/non-public audience", so I have to distribute it myself. I might try it again in the future, but their policy states that: "Add-ons that are intended for internal or private use, or are only accessible to a closed user group" will not be listed in the store, so I fear that it will remain this way.

In comparison, Chrome has no way to self-distribute, so I assume they allow a wider range of extensions.

Additionally, I'd like to mention that, while it is not in the store, the extension does update itself automatically, I added this specifically with version 1.2 (fortunately they provide a [method](https://extensionworkshop.com/documentation/manage/updating-your-extension/) to do this). So as long as you don't have the old version from October (which I hope very few still have installed), you will receive automatic updates as soon as a new version is released. I think I might have to add a sentence somewhere to mention the auto-update, as I can see that it is not obvious.
